CREATE TABLE VIDEO.ACTOR (
	ID_ACTOR INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL,
	FIRSTNAME VARCHAR(20) DEFAULT 'NULL',
	PRIMARY KEY (ID_ACTOR)
);

CREATE TABLE VIDEO.MOVIE (
	ID_MOVIE INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	COPIES INTEGER NOT NULL,
	MOVIE_TYPE VARCHAR(20) NOT NULL,
	MAIN_ACTOR_ID INTEGER DEFAULT NULL,
	PRIMARY KEY (ID_MOVIE)
);

CREATE TABLE VIDEO.MOVIE_SEC_ACTORS (
	ID_MOVIE INTEGER NOT NULL,
	ID_ACTOR INTEGER NOT NULL,
	PRIMARY KEY (ID_ACTOR,ID_MOVIE)
);

ALTER TABLE VIDEO.MOVIE
	ADD FOREIGN KEY (MAIN_ACTOR_ID) 
	REFERENCES VIDEO.ACTOR (ID_ACTOR);

ALTER TABLE VIDEO.MOVIE_SEC_ACTORS
	ADD FOREIGN KEY (ID_ACTOR) 
	REFERENCES VIDEO.ACTOR (ID_ACTOR);

ALTER TABLE VIDEO.MOVIE_SEC_ACTORS
	ADD FOREIGN KEY (ID_MOVIE) 
	REFERENCES VIDEO.MOVIE (ID_MOVIE);

INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('De Funes', 'Louis');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Reno', 'Jean');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Garcia', 'José');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Gere', 'Richard');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Stalone', 'Sylvester');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Bullock', 'Sandra');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Waver', 'Sigourney');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Di Caprio', 'Leonardo');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Winslett', 'Kate');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Barymore', 'Drew');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Statham', 'Jason');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Schwarzenegger', 'Arnold');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Roberts', 'Julia');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Pitt', 'Brad ');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Clooney', 'George');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Ford', 'Harrison');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Hamill', 'Mark');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Dujardin', 'Jean');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Hanks', 'Tom');
INSERT INTO VIDEO.ACTOR (LASTNAME, FIRSTNAME) 
	VALUES ('Damon', 'Matt');

INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Titanic', 8, 'Romance', 8);
INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Demolition man', 2, 'Action', 5);
INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Alien', 5, 'Fantastique', 7);
INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Expendables', 7, 'Action', 5);
INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Lucky luke', 410, 'Western', 18);
INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Star Wars', 4010, 'Fiction', 17);
INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Ocean''s Eleven', 0, 'Action', 15);
INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Da Vinci Code ', 2, 'Aventure', 19);
INSERT INTO VIDEO.MOVIE (TITLE, COPIES, MOVIE_TYPE, MAIN_ACTOR_ID) 
	VALUES ('Pretty Woman', 5, 'Romance', 13);

INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (8, 2);
INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (9, 4);
INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (2, 6);
INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (1, 9);
INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (4, 11);
INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (7, 13);
INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (7, 14);
INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (6, 16);
INSERT INTO VIDEO.MOVIE_SEC_ACTORS (ID_MOVIE, ID_ACTOR) 
	VALUES (7, 20);