package fr.utbm.entity;
// Generated 19 nov. 2016 10:33:10 by Hibernate Tools 4.3.1



/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private int id;
     private String title;
     private int copies;
     private String movieType;
     private Actor mainActor;

    public Movie() {
    }

	
    public Movie(int id, String title, int copies, String movieType) {
        this.id = id;
        this.title = title;
        this.copies = copies;
        this.movieType = movieType;
    }
    public Movie(int id, String title, int copies, String movieType, Actor mainActor) {
       this.id = id;
       this.title = title;
       this.copies = copies;
       this.movieType = movieType;
       this.mainActor = mainActor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getCopies() {
        return this.copies;
    }
    
    public void setCopies(int copies) {
        this.copies = copies;
    }
    public String getMovieType() {
        return this.movieType;
    }
    
    public void setMovieType(String movieType) {
        this.movieType = movieType;
    }
    public Actor getMainActor() {
        return this.mainActor;
    }
    
    public void setMainActor(Actor mainActor) {
        this.mainActor = mainActor;
    }




}


